### PR TITLE
add heat template for contextualization test

### PR DESCRIPTION
**Pull request by zhenz**

### CODE REVIEW

**Comment by zhenz** [comment]
@priteau @diurnalist Please review! Thank you!

**Comment by diurnalist** [comment]
I'm a bit confused by this repository - it claims to hold heat templates for complex appliances, but I only see one for network isolation - where are the others stored? I thought we had many more than this.

**Comment by priteau** [comment]
The other templates were never contributed to this repository. It's not too late to add them though!

**Comment by zhenz** [comment]
Add all templates in appliance catalog?

**Comment by priteau** [comment]
I would say the ones authored by / supported by Chameleon, such as the NFS appliance.

**Comment by zhenz** [comment]
@priteau @diurnalist I'll close this pull request and put this template to testing repo. 

I'll see later how to sync Chameleon supported templates to this repo.

Thanks!

**Comment by diurnalist** [comment]
FYI I have pulled in the two appliances we explicitly support: https://github.com/ChameleonCloud/heat-templates/pull/2

**Comment by zhenz** [comment]
Closing

**Pull request closed without merging**
